### ISSUE TITLE
Question of Repetitional Consistency

### ISSUE THREAD

**Issue by chanmuzi** [Slimshilin/Position-Bias-Analyzer#1]
@Slimshilin 
Hi! I'm a reader of your paper, Judging the Judges.
It was very impressive research for me, so I delved into the contents of the contents.

But I'm curious how RC can range from '0' to '1'.
Its numerator is $max(|c_1^j|, |c_2^j|)$, isn't it?
It means that the numerator's maximum value could be the same as the denominator, $t_j$.
And the minimum value of it could be at least the half value of the denominator.

I'm not sure what I'm missing at the moment, so please let me know if my understanding of the RC score is not correct.
Thanks!

**Comment by Slimshilin** [comment]
Hi @chanmuzi,

Thank you for loving our work! You are correct about understanding RC's computation - it actually ranges from a small but positive value to 1, i.e., (0,1]. For the Option-2 mode, you are correct that the minimum value should be at least half the value of the denominator; for more options (e.g., C and D or even E involved), the minimum value for RC can be smaller. For example, the Option-3 mode may have 33.3% RC.

Thank you for engaging in our research and posing this fantastic question. Hope this answers your question. If you have any more questions or concerns, we are more than happy to discuss them!
